# This is a basic workflow to help you get started with Actions

name: Check TimeZone Version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '* * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Edit XML
        uses: Mudlet/xmlstarlet-action@v1.1
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./src/System.Runtime.TimeZoneData/data/version

      # Check for updates to Timezone version
      - name: Check for updates
        run: dotnet build /t:CheckVersion
      - name: Set version from file
        run: echo {{ steps.version.outputs.content }}            
